var ContentProvider=(function(){var basicAuth,serverName,apiURL;var serverNameLive='www.kwsp.gov.my';var basicAuthLive='';var serverNameDev='kwsp.igndev.com';var basicAuthDev='';var default_lang='en_US';var lang=$('html').attr('lang');const GROUP_ID=20126;var _init=function(){var tmpUrl=window.location.href;var containerElem=$('.responsive-navi-mobile');var searchTextboxMobile=$('#txtSearchMobile');searchTextboxMobile.attr('name','q');var formElem=$('<form></form>');formElem.attr('name','frmSearchMobile');formElem.attr('action','/search');formElem.attr('method','GET');formElem.attr('enctype','multipart/form-data');formElem.attr('style','width:initial;margin-top:-54px;');searchTextboxMobile.detach().appendTo(formElem)
containerElem.prepend(formElem);if(tmpUrl.indexOf('kwsp.igndev.com')>-1){basicAuth=basicAuthDev;serverName=serverNameDev}else{basicAuth=basicAuthLive;serverName=serverNameLive}
serverName='//'+serverName;basicAuth='Basic '+basicAuth;apiURL=serverName+'/api/jsonws/invoke';if($('.orbit-bullets').length>0){$(window).on('resize',function(){if($(window).width()<768){$("figure.orbit-figure").each(function(index){var desktopImg=$.trim($(this).attr('img-desktop'));var mobileImg=$.trim($(this).attr('img-mobile'));if(mobileImg!=""){$(this).css('background-image','url('+mobileImg+')')}else{$(this).css('background-image','url('+desktopImg+')')}})}else{$("figure.orbit-figure").each(function(index){var desktopImg=$.trim($(this).attr('img-desktop'));$(this).css('background-image','url('+desktopImg+')')})}}).trigger('resize')}
var needHelpTitle='Need Help?';var needHelpCurrent='Please quote your EPF number or dentification Card number and the type of withdrawal applied for when contacting the EPF.';var needHelpNew='Please quote your EPF member number or identification number (NRIC/passport) and the subject of your query when contacting the EPF';if(lang=='ms-MY'){needHelpTitle='Perlukan Bantuan?';needHelpCurrent='Sila sertakan nombor ahli KWSP atau nombor IC anda dan juga tajuk soalan anda semasa menghubungi KWSP.';needHelpNew='Sila sertakan nombor ahli KWSP atau nombor kad pengenalan/pasport anda dan juga tajuk soalan anda semasa menghubungi KWSP.'}
var tmpElem=$('.grid-container .content_space');if(tmpElem!=null&&tmpElem!=undefined){var nextElem=tmpElem.next();if(nextElem!=null&&nextElem!=undefined){var h3=nextElem.children('h3');if(h3!=null&&h3!=undefined){var p=h3.next();if(p!=null&&p!=undefined){if(p.text()==needHelpCurrent){p.text(needHelpNew)}}}}}
if(document.URL.toLowerCase().indexOf('login-member')>-1||document.URL.toLowerCase().indexOf('login-employer')>-1){var currURL=document.URL.toLowerCase();var currURLArr=currURL.split('/');if($.trim(currURLArr[currURLArr.length-1])==''){if(currURLArr[currURLArr.length-2]=='login-member'||currURLArr[currURLArr.length-2]=='login-employer'){$('body').addClass('custom-body');$('body').addClass('custom-body-login')}}else{if(currURLArr[currURLArr.length-1]=='login-member'||currURLArr[currURLArr.length-1]=='login-employer'){$('body').addClass('custom-body');$('body').addClass('custom-body-login')}}}
lang=lang.replace('-','_');$(document).ready(function(){if(location.hash!=null&&location.hash!=undefined&&location.hash!=''){var hashtarget=$(location.hash);if(hashtarget.length==0){var hashName=location.hash;hashName=hashName.replace('#','');var aHash=$('a[name='+hashName+']');if(aHash.length==1){$('html,body').animate({scrollTop:aHash.offset().top-65},1)}}else{setTimeout(function(){if($('#appointmentform').length==0&&$('#propertiesContainer').length==0&&hashtarget.length>0){$('html,body').animate({scrollTop:hashtarget.offset().top},500)}},2000)}}
var kwspPages=$('.kwsp-page-names');var bannerCarousel=$('#banner-carousel');if(bannerCarousel.length==1){$('body').addClass('custom-body')}
var formIframe=$('#formContainerIFrame');if(formIframe!=null){var formNameToCheck='have questions about nomination? have questions about contribution? have questions about withdrawal? have questions about investment? have questions about offences and penalties? have questions about e-ctml? have questions about registration? have questions about simpanan shariah?';var formNameToCheck=[{en_US:'Have questions about Nomination?',ms_MY:'Ada pertanyaan mengenai Penamaan?'},{en_US:'Have questions about Contribution?',ms_MY:'Ada pertanyaan mengenai Caruman?'},{en_US:'Have questions about Withdrawal?',ms_MY:'Ada pertanyaan mengenai Pengeluaran?'},{en_US:'Have questions about Investment?',ms_MY:'Ada pertanyaan mengenai Pelaburan?'},{en_US:'Have questions about Offences and Penalties?',ms_MY:'Ada pertanyaan mengenai Kesalahan dan Penalti?'},{en_US:'Have questions about e-CTML?',ms_MY:'Ada pertanyaan mengenai e-CTML?'},{en_US:'Have questions about Registration?',ms_MY:'Ada pertanyaan mengenai Pendaftaran?'},{en_US:'Have questions about Simpanan Shariah?',ms_MY:'Ada pertanyaan mengenai Simpanan Shariah?'}]
var formData=formIframe.data('form-data');if(formData!=undefined){var formName=formData.name;var nameFound=!1;for(var d=0;d<formNameToCheck.length;d++){if(formNameToCheck[d].en_US.toLowerCase()==formName.toLowerCase()){formName=formNameToCheck[d][lang];nameFound=!0;break}}
if(!nameFound){if(formData!=undefined&&formData!=''){_getForm(formIframe,formData)}}else{var buttonCaption='Submit your enquiry';if(lang=='ms_MY'){buttonCaption='Hantar pertanyaan anda'}
formIframe.css('height','231px');formIframe.append('<h3>'+formName+'</h3>');formIframe.append('<div style="margin-top:30px;"><div class="button gold-bg long"><a href="/reach-us/connect-with-us/make-an-enquiry">'+buttonCaption+'</a></div></div>')}}}
var currentUrl=document.URL;var iframe=$('#form_contribution');$('#form_contribution').on('load',function(){var cssLink=document.createElement("link")
cssLink.href="/documents/20126/0/form-style.css/e6532ff4-9439-79e7-3ec2-81207bad6a23";cssLink.rel="stylesheet";cssLink.type="text/css";var iframeDoc=window.frames.form_contribution.document;var iframeHead=iframeDoc.head;iframeHead.appendChild(cssLink)});var faq=$('#faqContainer');if(faq!=null){var folderName=faq.data('faq-folder');if(folderName!=undefined&&folderName!=''){_getFAQ(faq,folderName)}}
$('#faq_category').on('change',function(){var selected=$('#faq_category option:selected');_getFAQ(faq,selected.val())})});$('#btnSearchOffices').on('click',function(e){e.preventDefault();var selectedState=$('#ddlState option:selected').val();var selectedType=$('#ddlType option:selected').val();$('#divOffices, #divOfficesSeparator, #divKiosks, #divKiosksSeparator, #divThirdParty').hide();if(selectedType=='all'){$('#divOffices, #divOfficesSeparator, #divKiosks, #divKiosksSeparator, #divThirdParty').show();$("#tabOffices").parent().parent().foundation('down',$("#tabOffices"));_getOfficesKiosk('Offices',selectedState,$('#officesResults'),$('#officesContainer'));_getOfficesKiosk('Kiosks',selectedState,$('#kiosksResults'),$('#kiosksContainer'));_getOfficesKiosk('Third Party Kiosks',selectedState,$('#thirdPartyKiosksResults'),$('#thirdPartyKiosksContainer'))}
if(selectedType=='offices'){$('#divOffices').show();$("#tabOffices").parent().parent().foundation('down',$("#tabOffices"));_getOfficesKiosk('Offices',selectedState,$('#officesResults'),$('#officesContainer'))}
if(selectedType=='kiosks'){$('#divKiosks').show();$("#tabKiosks").parent().parent().foundation('down',$("#tabKiosks"));_getOfficesKiosk('Kiosks',selectedState,$('#kiosksResults'),$('#kiosksContainer'))}
if(selectedType=='3rdpartkiosks'){$('#divThirdParty').show();$("#tab3rdParty").parent().parent().foundation('down',$("#tab3rdParty"));_getOfficesKiosk('Third Party Kiosks',selectedState,$('#thirdPartyKiosksResults'),$('#thirdPartyKiosksContainer'))}
if(selectedType=='ras'){$('#divOffices').show();$("#tabOffices").parent().parent().foundation('down',$("#tabOffices"));_getOfficesKiosk('RAS',selectedState,$('#officesResults'),$('#officesContainer'))}});$('ul.accordion').on('down.zf.accordion',function(e,panel){var selectedState=$('#ddlState option:selected').val();var state='';if(panel.data('location-type')=='offices'){if($('#ddlType option:selected').val()=='ras'){_getOfficesKiosk('RAS',selectedState,$('#officesResults'),$('#officesContainer'))}else{_getOfficesKiosk('Offices',selectedState,$('#officesResults'),$('#officesContainer'))}}
if(panel.data('location-type')=='kiosks'){_getOfficesKiosk('Kiosks',selectedState,$('#kiosksResults'),$('#kiosksContainer'))}
if(panel.data('location-type')=='thirdpartykiosks'){_getOfficesKiosk('Third Party Kiosks',selectedState,$('#thirdPartyKiosksResults'),$('#thirdPartyKiosksContainer'))}});$('ul.accordion').on('up.zf.accordion',function(e,$panel){})};var _getOfficesKiosk=function(type,filterState,resultCountContainer,dataContainer){var dstamp=new Date();var strstamp=dstamp.getFullYear()+""+dstamp.getMonth()+""+dstamp.getDate();if(type=='Third Party Kiosks'){$.ajax({url:'/documents/20126/138305/all.json/cb98549a-6237-00e0-23a9-1327edec3ce9?ts='+strstamp,type:'GET',success:function(response){var tmpl='';var filtered=response;if(filterState!='all'){filtered=response.filter(function(kiosk){return kiosk.state==filterState})}
var result=filtered.length+' result'+((filtered.length>1)?'s':'');if(lang=='in_ID'||lang=='ms_MY'){result=filtered.length+' dijumpai'}
resultCountContainer.html(result);filtered.forEach(function(value){var branchName=value.branch;var viewMap='LOCATION MAP';var office='Office';var counter='Counter'
var operatingHours='Operating Hours'
var services='Services';var details='Details';if(lang=='ms_MY'){branchName=branchName.replace('EPF','KWSP');viewMap='PETA LOKASI';office='Pejabat';counter='Kaunter'
operatingHours='Masa Operasi';services='Perkhidmatan';details='Maklumat'}
branchName=branchName.replace(/\(/gi,'<br>(');tmpl+='<table class="location_table2 multablecnt">\n';tmpl+='   <tbody>\n';tmpl+='      <tr>\n';tmpl+='         <td data-label="'+details+'">\n';tmpl+='            <div class="block">\n';tmpl+='               <h4 class="blue">'+branchName+'</h4>\n';tmpl+='               <p></p>\n';tmpl+='               <div class="inlineblock flex-row-left mb2">\n';tmpl+='               </div>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='         <td data-label="'+operatingHours+'">\n';tmpl+='            <div class="block">\n';var masaBekerja=value.operationalHours;if(lang=='ms_MY'){var m=value.operationalHours;m=m.replace(/Open last Sunday every month/gi,'Buka Ahad terakhir setiap bulan');m=m.replace(/Closed every fourth Saturday of the month/gi,'Tutup setiap hari Sabtu ke-4');m=m.replace(/Friday Break/gi,'Rehat Jumaat');m=m.replace(/Sunday/g,'Ahad');m=m.replace(/Monday/g,'Isnin');m=m.replace(/Wednesday/g,'Rabu');m=m.replace(/Thursday/g,'Khamis');m=m.replace(/Friday/g,'Jumaat');m=m.replace(/Saturday/g,'Sabtu');m=m.replace(/Subject to Public Holidays/gi,'Tertakluk kepada cuti umum');masaBekerja=m}
tmpl+='               <p>'+masaBekerja+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='         <td data-label="'+services+'">\n';tmpl+='            <div class="block">\n';tmpl+='              <p>'+value.address+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='      </tr>\n';tmpl+='   </tbody>\n';tmpl+='</table>\n'});dataContainer.html(tmpl)},error:function(e){console.log('ERROR: ',e)}})}else{var postData={'/journal.journalfolder/get-folders':{'groupId':'20126'}};var officesKiosksFolderName=type.toLowerCase();if(type=='RAS'){officesKiosksFolderName='offices'}
$.ajax({url:apiURL,type:'GET',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=t8g375tQ',beforeSend:function(xhr){},success:function(folders){var folderIds=[];if(folders){$.each(folders,function(key,value){if(value.name.toLowerCase()==officesKiosksFolderName){folderIds.push(value.folderId)}})}
if(folderIds.length>0){postData={'/journal.journalarticle/get-articles':{'groupId':'20126','folderId':folderIds[0]}};$.ajax({url:apiURL,type:'POST',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=oliBqOjC',beforeSend:function(xhr){},success:function(data){var offices=[];$.each(data,function(key,value){var office={OfficeKioskName:null,KioskCode:null,OfficeKioskAddress:null,OfficeKioskState:null,OfficeKioskMapURL:null,OfficeKioskMapURLWaze:null,OfficeKioskPhoneNumber:null,OfficeKioskFaxNumber:null,OperatingHoursOfficeKiosk:[],OperatingHoursCounter:[],OfficeKioskServices:[],articleContent:null,};try{var xml=$.parseXML(value.content);if(xml){var officeNode=xml.childNodes[0];var langContentAvailable=!1;$.each(officeNode.childNodes,function(key,value){if(value.nodeName=='dynamic-element'){var fieldName=value.attributes.name.nodeValue;var fieldNames='OfficeKioskName KioskCode OfficeKioskAddress OfficeKioskState OfficeKioskMapURL OfficeKioskMapURLWaze OfficeKioskPhoneNumber OfficeKioskFaxNumber OperatingHoursOfficeKiosk OperatingHoursCounter OfficeKioskServices';if(fieldNames.indexOf(fieldName)>-1){$.each(value.childNodes,function(key,value){if(value.nodeName=='dynamic-content'){if(value.attributes['language-id'].nodeValue==lang){langContentAvailable=!0;if(fieldName!='OperatingHoursOfficeKiosk'&&fieldName!='OperatingHoursCounter'&&fieldName!='OfficeKioskServices'){office[fieldName]=value.textContent}else{office[fieldName].push(value.textContent)}}else if(value.attributes['language-id'].nodeValue!=lang&&value.attributes['language-id'].nodeValue=='en_US'&&!langContentAvailable){if(fieldName!='OperatingHoursOfficeKiosk'&&fieldName!='OperatingHoursCounter'&&fieldName!='OfficeKioskServices'){if(office[fieldName]==null){office[fieldName]=value.textContent}}else{office[fieldName].push(value.textContent)}}}})}}});if(filterState!='all'){if(office.OfficeKioskState==filterState){offices.push(office)}}else{offices.push(office)}}}catch(ex){console.log('Error: ',ex)}
if(value.status==0){}});var tmpOffices=[];if(type=='RAS'){for(var n=0;n<offices.length;n++){var m=offices[n];var include=!1;for(var s=0;s<m.OfficeKioskServices.length;s++){var service=m.OfficeKioskServices[s];if(service.indexOf('RAS')>-1){include=!0;break}}
if(include){tmpOffices.push(m)}}
offices=tmpOffices}
offices.sort(_predicateBy('OfficeKioskName'));var result=offices.length+' result'+((offices.length>1)?'s':'');if(lang=='in_ID'||lang=='ms_MY'){result=offices.length+' dijumpai'}
resultCountContainer.html(result);var tmpl='';$.each(offices,function(key,value){var branchName=value.OfficeKioskName;var viewMap='LOCATION MAP';var office='Office';var counter='Counter'
var operatingHours='Operating Hours'
var services='Services';var details='Details';if(lang=='ms_MY'){branchName=branchName.replace('EPF','KWSP');viewMap='PETA LOKASI';office='Pejabat';counter='Kaunter'
operatingHours='Masa Operasi';services='Perkhidmatan';details='Maklumat'}
if(type.toLowerCase()=='offices'||type.toLowerCase()=='ras'){tmpl+='<table class="location_table multablecnt">\n';tmpl+='   <tbody>\n';tmpl+='      <tr>\n';tmpl+='         <td data-label="'+details+'">\n';tmpl+='            <div class="block">\n';tmpl+='               <h4 class="blue">'+branchName+'</h4>\n';tmpl+='               <p>'+value.OfficeKioskAddress+'</p>\n';tmpl+='               <div class="inlineblock flex-row-left mb2">\n';tmpl+='                  <a class="button mb0" href="'+value.OfficeKioskMapURL+'" target="_blank">'+viewMap+'</a>\n';if($.trim(value.OfficeKioskMapURLWaze)!=""){tmpl+='                  <a class="show-for-small-only" href="'+value.OfficeKioskMapURLWaze+'"><img src="/o/kwsp-theme/css/assets/img/waze.png" /></a>\n'}
tmpl+='               </div>\n';tmpl+='               <p>Fax: '+value.OfficeKioskFaxNumber+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='         <td data-label="'+operatingHours+'">\n';tmpl+='            <div class="block">\n';tmpl+='               <h4 class="blue">'+office+'</h4>\n';var masaBekerja='';$.each(value.OperatingHoursOfficeKiosk,function(key,value){var m=value;if(lang=='ms_MY'){m=m.replace(/Closed every fourth Saturday of the month/gi,'Tutup setiap hari Sabtu ke-4');m=m.replace(/Fri Break/gi,'Rehat Jumaat');m=m.replace(/Sun/g,'Ahad');m=m.replace(/Mon/g,'Isnin');m=m.replace(/Wed/g,'Rabu');m=m.replace(/Thu/g,'Khamis');m=m.replace(/Fri/g,'Jumaat');m=m.replace(/Sat/g,'Sabtu');m=m.replace(/Subject to Public Holidays/gi,'Tertakluk kepada cuti umum')}
masaBekerja+=m+'<br>'});tmpl+='               <p>'+masaBekerja+'</p>\n';tmpl+='               <h4 class="blue">'+counter+'</h4>\n';var masaKaunterDibuka='';$.each(value.OperatingHoursCounter,function(key,value){var m=value;if(lang=='ms_MY'){m=m.replace(/Closed every fourth Saturday of the month/gi,'Tutup setiap hari Sabtu ke-4');m=m.replace(/Fri Break/gi,'Rehat Jumaat');m=m.replace(/Sun/g,'Ahad');m=m.replace(/Mon/g,'Isnin');m=m.replace(/Wed/g,'Rabu');m=m.replace(/Thu/g,'Khamis');m=m.replace(/Fri/g,'Jumaat');m=m.replace(/Sat/g,'Sabtu');m=m.replace(/Subject to Public Holidays/gi,'Tertakluk kepada cuti umum')}
masaKaunterDibuka+=m+'<br>'});tmpl+='               <p>'+masaKaunterDibuka+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='      </tr>\n';tmpl+='   </tbody>\n';tmpl+='</table>\n\n'}
if(type.toLowerCase()=='kiosks'){tmpl+='<table class="location_table multablecnt">\n';tmpl+='   <tbody>\n';tmpl+='      <tr>\n';tmpl+='         <td data-label="'+details+'">\n';tmpl+='            <div class="block">\n';tmpl+='               <h4 class="blue">'+branchName+'</h4>\n';tmpl+='               <p>'+value.OfficeKioskAddress+'</p>\n';tmpl+='               <div class="inlineblock flex-row-left mb2">\n';tmpl+='                  <a class="button mb0" href="'+value.OfficeKioskMapURL+'" target="_blank">'+viewMap+'</a>\n';if($.trim(value.OfficeKioskMapURLWaze)!=""){tmpl+='                  <a class="show-for-small-only" href="'+value.OfficeKioskMapURLWaze+'"><img src="/o/kwsp-theme/css/assets/img/waze.png" /></a>\n'}
tmpl+='               </div>\n';tmpl+='               <p>Fax: '+value.OfficeKioskFaxNumber+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='         <td data-label="'+operatingHours+'">\n';tmpl+='            <div class="block">\n';var masaBekerja='';$.each(value.OperatingHoursOfficeKiosk,function(key,value){var m=value;if(lang=='ms_MY'){m=m.replace(/Closed every fourth Saturday of the month/gi,'Tutup setiap hari Sabtu ke-4');m=m.replace(/Fri Break/gi,'Rehat Jumaat');m=m.replace(/Sun/g,'Ahad');m=m.replace(/Mon/g,'Isnin');m=m.replace(/Wed/g,'Rabu');m=m.replace(/Thu/g,'Khamis');m=m.replace(/Fri/g,'Jumaat');m=m.replace(/Sat/g,'Sabtu');m=m.replace(/Subject to Public Holidays/gi,'Tertakluk kepada cuti umum')}
masaBekerja+=m+'<br>'});tmpl+='               <p>'+masaBekerja+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='      </tr>\n';tmpl+='   </tbody>\n';tmpl+='</table>\n'}
if(type.toLowerCase()=='third party kiosks'){tmpl+='<table class="location_table2 multablecnt">\n';tmpl+='   <tbody>\n';tmpl+='      <tr>\n';tmpl+='         <td data-label="'+details+'">\n';tmpl+='            <div class="block">\n';tmpl+='               <h4 class="blue">'+branchName+((value.KioskCode!='')?'<br>('+value.KioskCode+')':'')+'</h4>\n';tmpl+='               <p></p>\n';tmpl+='               <div class="inlineblock flex-row-left mb2">\n';tmpl+='                  <a class="button mb0" href="'+value.OfficeKioskMapURL+'" target="_blank">'+viewMap+'</a> \n';if($.trim(value.OfficeKioskMapURLWaze)!=""){tmpl+='                  <a class="show-for-small-only" href="'+value.OfficeKioskMapURLWaze+'"><img src="/o/kwsp-theme/css/assets/img/waze.png" /></a>\n'}
tmpl+='               </div>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='         <td data-label="'+operatingHours+'">\n';tmpl+='            <div class="block">\n';var masaBekerja='';$.each(value.OperatingHoursOfficeKiosk,function(key,value){var m=value;if(lang=='ms_MY'){m=m.replace(/Closed every fourth Saturday of the month/gi,'Tutup setiap hari Sabtu ke-4');m=m.replace(/Fri Break/gi,'Rehat Jumaat');m=m.replace(/Sun/g,'Ahad');m=m.replace(/Mon/g,'Isnin');m=m.replace(/Wed/g,'Rabu');m=m.replace(/Thu/g,'Khamis');m=m.replace(/Fri/g,'Jumaat');m=m.replace(/Sat/g,'Sabtu');m=m.replace(/Subject to Public Holidays/gi,'Tertakluk kepada cuti umum')}
masaBekerja+=m+'<br>'});tmpl+='               <p>'+masaBekerja+'</p>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='         <td data-label="'+services+'">\n';tmpl+='            <div class="block">\n';tmpl+='               <ul>\n';var servisKiosk='';$.each(value.OfficeKioskServices,function(key,value){var m=value;if(lang=='ms_MY'){m=m.replace(/TAC Activation/gi,'Pengaktifan TAC');m=m.replace(/i-Akaun Registration/gi,'Pendaftaran i-Akaun');m=m.replace(/Print Statement/gi,'Cetak Penyata')}
tmpl+='                  <li>'+m+'</li>\n'});tmpl+='               </ul>\n';tmpl+='            </div>\n';tmpl+='         </td>\n';tmpl+='      </tr>\n';tmpl+='   </tbody>\n';tmpl+='</table>\n'}});dataContainer.html(tmpl)},error:function(error){console.log(error)}})}},error:function(error){console.log('ERROR: ',error)}})}};var _getFAQ=function(container,folderName){var groupIds=[20126];var keyword='Frequently';container.empty();var postData={'/journal.journalfolder/get-folders':{'groupId':groupIds[0]}};$.post({url:apiURL,type:'POST',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=t8g375tQ',beforeSend:function(xhr){},success:function(folders){var folderIds=[];var faqID=0;var tmp=[];$.each(folders,function(key,value){var folder=value;var folderID=parseInt(folder.folderId);if(folderName.toLowerCase()=='all'){if(folder.name.toLowerCase()=='faq'){faqID=folderID}
if(faqID!=0&&folder.name.indexOf('/')<0){if(folder.parentFolderId==faqID){folderIds.push({id:folderID,name:folder.name,parentId:folder.parentFolderId});tmp.push({id:folderID,name:folder.name,parentId:folder.parentFolderId})}}}else{if(folder.name.toLowerCase()==folderName.toLowerCase()){folderIds.push({id:folderID,name:folder.name,parentId:folder.parentFolderId})}}});if(folderName=='all'){var category=lang=='en_US'?'ALL CATEGORIES':'SEMUA KATEGORI';tmp.sort(_sortDesc('name'));$('#sub_category').hide();$('#faq_category').empty();$('#faq_category').append('<option value="all">'+category+'</option>');$.each(tmp,function(key,value){var arr=value.name.split(' - ');var x=arr.length;var name=arr[x-1];var faqFolderName=name;var memberOrEmployer=arr[0];if(lang=='in_ID'||lang=='ms_MY'){memberOrEmployer=memberOrEmployer=='Member'?'Ahli':'Majikan'}
name=name.replace(' or ','/');$.each($('.kwsp-page-names'),function(key,value){var inpHidden=$(value);if(inpHidden.val().toString().toLowerCase()==name.toString().toLowerCase()){faqFolderName=inpHidden.val();if(lang=='in_ID'||lang=='ms_MY'){faqFolderName=inpHidden.data('language-ms')}}});$('#faq_category').append('<option value="'+value.name+'">'+memberOrEmployer+' - '+faqFolderName+'</option>')})}
folderIds.sort(_sortDesc('name'));if(folderIds.length>0){$.each(folderIds,function(key,value){var faqFolder=value;postData={'/journal.journalarticle/get-articles':{'groupId':groupIds[0],'folderId':faqFolder.id,'status':'0','start':'0','end':'1000','-obc':''}};$.post({url:apiURL,type:'POST',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=oliBqOjC',beforeSend:function(xhr){},success:function(data){var faqs=[];var faqQuestion='';var articleId='';data.sort(_sortAsc('articleId'));$.each(data,function(key,value){var faq={question:null,answer:null,dateModified:value.modifiedDate,displayOrder:null,en_US:null,in_ID:null,ms_MY:null};if(value.articleId!=articleId&&value.status==0){var xml=$.parseXML(value.content);if(xml){var faqNode=xml.childNodes[0];$.each(faqNode.childNodes,function(key,value){if(value.nodeName=='dynamic-element'){var fieldName=value.attributes.name.nodeValue;if(fieldName=='FaqQuestion'||fieldName=='FaqAnswer'||fieldName=='DisplayOrder'){$.each(value.childNodes,function(key,value){if(value.nodeName=='dynamic-content'){if(value.attributes['language-id'].nodeValue==lang){if(fieldName=='FaqQuestion')faq.question=value.textContent;if(fieldName=='FaqAnswer')faq.answer=value.textContent;if(fieldName=='DisplayOrder'){var convNum=Number(value.textContent);if(convNum!=NaN){faq.displayOrder=convNum}else{faq.displayOrder=0}}}
if(faq.question==null){if(value.attributes['language-id'].nodeValue=='en_US'){if(fieldName=='FaqQuestion')faq.question=value.textContent}}
if(faq.answer==null){if(value.attributes['language-id'].nodeValue=='en_US'){if(fieldName=='FaqAnswer')faq.answer=value.textContent}}
if(faq.displayOrder==null){faq.displayOrder=0}}})}}});faqs.push(faq)}}
articleId=value.articleId});faqs.sort(_sortAsc('displayOrder'));var elem='';if(faqs.length>0){var arr=faqFolder.name.split(' - ');var n=arr.length;var faqFolderName=arr[n-1];faqFolderName=faqFolderName.replace(' or ','/');var memberOrEmployer=arr[0];if(lang=='in_ID'||lang=='ms_MY'){memberOrEmployer=memberOrEmployer=='Member'?'Ahli':'Majikan'}
$.each($('.kwsp-page-names'),function(key,value){var inpHidden=$(value);if(inpHidden.val().toString().toLowerCase()==faqFolderName.toString().toLowerCase()){faqFolderName=inpHidden.val();if(lang=='in_ID'||lang=='ms_MY'){faqFolderName=inpHidden.data('language-ms')}}});elem+='<ul id="faqHeader" class="grid-x grid-margin-x accordion" data-accordion="" data-allow-all-closed="true">';elem+='<li class="accordion-item cell small-12" data-accordion-item="">';elem+='<a class="accordion-title" href="#">'+memberOrEmployer+' - '+faqFolderName+'</a>';elem+='<div class="accordion-content" data-tab-content role="tabpanel" aria-hidden="true">';elem+='<ul id="faqCategory" class="grid-x grid-margin-x accordion" data-accordion="" data-allow-all-closed="true">';$.each(faqs,function(key,value){elem+='<li class="accordion-item cell small-12" data-accordion-item>\n';elem+='   <a href="#" class="accordion-title acc-faq acc-faq-title transbg">'+value.question+'</a>\n';elem+='   <div class="accordion-content acc-faq-content transbg" data-tab-content>\n';elem+='      '+value.answer+'\n';elem+='   </div>\n';elem+='</li>\n'})
elem+='</ul>';elem+='</div>';elem+='</li>';elem+='</ul>';container.append(elem);try{$('#faqContainer ul#faqHeader').foundation();$('#faqContainer ul#faqCategory').foundation()}catch(e){}}},error:function(ex){console.log(ex)}})})}},error:function(ex){console.log(ex.message)}})};var _getForm=function(container,formData){var postData={'/ddm.ddmforminstance/get-form-instances':{'companyId':'20099','groupId':'20126','start':'0','end':'20'}};$.post({url:apiURL,type:'POST',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=ugat7C1N',beforeSend:function(xhr){},success:function(data){if(data.length>0){var selectedFormInstanceID=-1;$.each(data,function(key,value){if(value.nameCurrentValue.toString().toLowerCase()==formData.name.toLowerCase()){selectedFormInstanceID=parseInt(value.formInstanceId)}});if(selectedFormInstanceID>0){var iframe=$('<iframe src="/web/forms/shared/-/form/'+selectedFormInstanceID+'" frameborder="0" height="0" scrolling="no" id="form_contribution" name="form_contribution" style="height:0; width:'+formData.width+'"></iframe>');iframe.on('load',function(){var cssLink=document.createElement("link")
cssLink.href="/documents/20126/0/form-style.css/e6532ff4-9439-79e7-3ec2-81207bad6a23";cssLink.rel="stylesheet";cssLink.type="text/css";var iframeWnd=window.frames.form_contribution;var iframeDoc=iframeWnd.document;var iframeHead=iframeDoc.head;iframeHead.appendChild(cssLink);if(lang!='en_US'){var elmnt=iframeDoc.getElementsByClassName('lfr-ddm-form-submit')[0];elmnt.innerHTML="Hantar"}
if(formData.name=='Have questions about Contribution?'){if(lang=='en_US'){container.append('<h4>Or visit</h4><p class="know_more">Your nearest <a href="/reach-us/offices-kiosks" target="_blank" rel="noopener noreferrer">EPF office</a></p>')}else{container.append('<h4>Atau kunjungi</h4><p class="know_more"><a href="/reach-us/offices-kiosks" target="_blank" rel="noopener noreferrer">Pejabat KWSP</a> yang berdekatan </p>')}}
$(iframeDoc).load=function(){};$(iframeDoc).on('load',function(){});$(iframeDoc).on('resize',function(){});setInterval(function(){iframe.css('height',iframeDoc.body.offsetHeight+'px')},200);iframe.css('height',formData.height)});container.empty();container.append(iframe)}}},error:function(){}})};var _getBoardMembers=function(){var groupIds=[20126];container.empty();var postData={'/journal.journalfolder/get-folders':{'groupId':GROUP_ID}};$.post({url:apiURL,type:'POST',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=t8g375tQ',beforeSend:function(xhr){},success:function(folders){var folderInfo=[];$.each(folders,function(key,value){var folder=value;if(folder.folderName.toLowerCase()=='board members'||folder.folderName.toLowerCase()=='investment panel'||folder.folderName.toLowerCase()=='senior management'){folderInfo.push({id:folder.folderId,name:folder.name,parentId:folder.parentFolderId})}});if(folderInfo.length>0){$.each(folderInfo,function(key,value){var folder=value;postData={'/journal.journalarticle/get-articles':{'groupId':GROUP_ID,'folderId':folder.id,'status':'0','start':'0','end':'1000','-obc':''}};$.post({url:apiURL,type:'POST',dataType:'json',data:'cmd='+escape(JSON.stringify(postData))+'&p_auth=t8g375tQ',beforeSend:function(xhr){},success:function(articles){},error:function(){}})})}},error:function(){}})};var _predicateBy=function(prop){return function(a,b){if(a[prop]>b[prop]){return 1}else if(a[prop]<b[prop]){return-1}
return 0}};var _sortAsc=function(prop){return function(a,b){if(a[prop]>b[prop]){return 1}else if(a[prop]<b[prop]){return-1}
return 0}};var _sortDesc=function(prop){return function(a,b){if(a[prop]>b[prop]){return-1}else if(a[prop]<b[prop]){return 1}
return 0}};return{init:_init}})()